
version: 2

models:
  - name: dim_airports
    columns:
      - name: airport_code
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_aircrafts
    columns:
      - name: aircraft_code
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
sources:
  - name: stg
    database: flights_demo
    schema: stg
    tables: 
      - name: airports_data
      - name: aircrafts_data
      - name: seats